# Generated by Django 4.1.7 on 2023-03-25 22:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('kvantum', models.CharField(choices=[('VR', 'Vr'), ('IT', 'It'), ('MEDIA', 'Media'), ('IND-DESIGN', 'Ind-Design'), ('ENERGY', 'Energy'), ('BIO', 'Bio'), ('NEURO', 'Neuro'), ('NANO', 'Nano'), ('HI-TECH', 'Hi-Tech'), ('GEO', 'Geo'), ('AERO', 'Aero'), ('IND-ROBO', 'Ind-Robo')], max_length=10, verbose_name='Квантум')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('contacts', models.ManyToManyField(to='base.contacts', verbose_name='Кониакты учеников')),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Image_Face', to='base.image', verbose_name='Обложка на главной странице')),
                ('image', models.ManyToManyField(blank=True, null=True, to='base.image', verbose_name='Дополнительные изображения')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_type', to='base.project', verbose_name='Что за проект'),
        ),
    ]
