# Generated by Django 4.2.3 on 2023-09-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(null=True, to='base.competitions'),
        ),
    ]
