# Generated by Django 4.2.5 on 2023-09-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_account_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
    ]
