# Generated by Django 4.2.5 on 2023-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contacts',
        ),
        migrations.AddField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(to='base.account', verbose_name='Создатели проектов'),
        ),
        migrations.AlterField(
            model_name='project',
            name='face',
            field=models.ImageField(upload_to='images/', verbose_name='Лицевое изображение'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
