# Generated by Django 4.2.5 on 2023-09-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_project_contacts_project_creators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='base.competitions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='base.project'),
        ),
    ]
