# Generated by Django 4.2.4 on 2023-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_account_favorite_alter_account_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='base.group'),
        ),
    ]
