# Generated by Django 4.2.4 on 2023-09-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_account_isteacher_alter_account_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='request_buy',
        ),
    ]
