# Generated by Django 4.2.1 on 2023-11-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_account_unique_together_remove_account_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
