# Generated by Django 4.2.6 on 2023-11-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_account_contact_project_pdfdescription'),
        ('base', '0014_project_addition'),
    ]

    operations = [
    ]
