# Generated by Django 4.2.6 on 2023-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20231122_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='addition',
        ),
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.CharField(max_length=200, null=True, verbose_name='Контакты'),
        ),
    ]
