# Generated by Django 4.2.6 on 2023-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_competitions_comment_project_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(to='base.account', verbose_name='projects'),
        ),
    ]
