# Generated by Django 4.2.6 on 2023-12-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_account_projects_alter_project_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='buys',
            field=models.ManyToManyField(null=True, to='base.buy'),
        ),
    ]
