# Generated by Django 4.2.6 on 2023-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_account_buys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(related_name='projects', to='base.account', verbose_name='Создатели проекта'),
        ),
    ]
