# Generated by Django 4.0.2 on 2024-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_project_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tag',
            field=models.CharField(default='nice', max_length=20, verbose_name='Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='buys',
            field=models.ManyToManyField(null=True, to='base.Buy'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='base.Competitions'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='base.Image', verbose_name='Дополнительные изображения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pupils',
            field=models.ManyToManyField(blank=True, null=True, to='base.Account'),
        ),
        migrations.AlterField(
            model_name='group',
            name='timetable',
            field=models.ManyToManyField(to='base.Timetable', verbose_name='Дни учёбы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, to='base.Comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(related_name='projects', to='base.Account', verbose_name='Создатели проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='base.Image', verbose_name='Дополнительные изображения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='base.Competitions'),
        ),
    ]
