# Generated by Django 4.0.2 on 2024-02-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_account_tag_alter_account_buys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tag'),
        ),
    ]
